% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={assessment-final-mt},
  pdfauthor={My My Tran},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{assessment-final-mt}
\author{My My Tran}
\date{2024-06-22}

\begin{document}
\maketitle

\section{Introduction}\label{introduction}

Network meta-analysis (NMA) allows for the comparative relative efficacy
and acceptability of interventions, such as galcanezumab and other
treatments for chronic migraine, through randomized controlled trials
(RCTs) {[}1{]}. These clinical trials form a network of observational
evidence, allowing for both direct and indirect comparisons. Prior to
this NMA, a feasibility assessment was completed, revealing minimal
concerns regarding heterogeneity across studies, implying that an NMA is
appropriate. This NMA evaluates the reduction in monthly migraine days
for galcanezumab in comparison to other treatments, including key
comparators such as Botox A, eptinezumab, erenumab, and placebo.

\section{Data and Methods}\label{data-and-methods}

This dataset is based on multiple 12-week observational studies of
clinical trials conducted on participants, on their reduction in monthly
migraine days from baseline to Week 12. It is comprised of the relative
mean difference versus placebo in the reduction of monthly migraine days
(y), the standard error in the mean difference (se), and the number of
treatment arms in the study (na).

We transform the data from long format into a pairwise format,
separating the treatment types into treatment 1 and treatment 2. These
studies provide direct comparisons against the placebo. Using placebo as
the common comparator, we can estimate the relative efficacy between two
interventions indirectly.

When constructing the network meta-analysis, comparisons with missing
treatment effect point estimates (TE), seTE, zero TE values are not
considered in the analysis. Therefore, two studies, Jones (1995), Gaudi
(2001), are excluded, which loses pieces of evidence for the treatments
galcanezumab and erenumab, respectively. Additionally, there is one
three-arm study in this dataset. Since each comparison in the three-arm
study should have its own effect size and standard error, we provide
data for each pairwise comparison {[}2{]}. This includes (1)
galcanezumab vs placebo, (2) galcanezumab vs eptinezumab, and (3)
placebo vs eptinezumab. Given the MD and SE between galcanezumab and
placebo, it is estimated that the MD between galcanezumab and
eptinezumab is 0.70 and the SE is 0.7401.

Therefore, the NMA includes data from 11 RCTS, comprising 13 pairwise
comparisons among 5 treatments (Botox A, eptinezumab, erenumab,
galcanezumab, and placebo).

The method used was a Frequentist random effects model to account for
heterogeneity or variability across studies, even if minimal. We are
interested in the random effects model as it allows for the possibility
that true effect sizes vary across studies. The studies can differ in
patient populations, methodologies, and other treatment-influencing
factors {[}3{]}. Assumptions of the Frequentist method include
transitivity, which are different treatments that are similar in
severity of chronic migraines, treatment dose or study quality, and
congruence and consistency {[}4{]}.

To conduct the NMA using the Frequentist approach, we use the netmeta
package in R {[}5{]}. The chosen reference treatment, or the baseline
against which all other treatments are compared is the placebo. This
allows us to see how galcanezumab and other treatments compare to this
same baseline {[}6{]}.

\section{Results}\label{results}

\begin{verbatim}
## -- Attaching packages --------------------------------------- tidyverse 1.3.2 --
## v ggplot2 3.4.0      v purrr   0.3.5 
## v tibble  3.1.8      v dplyr   1.0.10
## v tidyr   1.2.1      v stringr 1.5.0 
## v readr   2.1.3      v forcats 0.5.2 
## -- Conflicts ------------------------------------------ tidyverse_conflicts() --
## x dplyr::filter() masks stats::filter()
## x dplyr::lag()    masks stats::lag()
## Loading required package: meta
## 
## Loading required package: metadat
## 
## Loading 'meta' package (version 7.0-0).
## Type 'help(meta)' for a brief overview.
## Readers of 'Meta-Analysis with R (Use R!)' should install
## older version of 'meta' package: https://tinyurl.com/dt4y5drs
## 
## Loading 'netmeta' package (version 2.9-0).
## Type 'help("netmeta-package")' for a brief overview.
## Readers of 'Meta-Analysis with R (Use R!)' should install
## older version of 'netmeta' package: https://tinyurl.com/kyz6wjbb
\end{verbatim}

\begin{figure}
\centering
\includegraphics{final-assessment-mt_files/figure-latex/fig-1-1.pdf}
\caption{This is a graphical visualization of the network meta-analysis,
which compares all treatments within the network. The nodes represent
interventions (treatment types), and edges are direct comparisons,
weighted by the number of studies. Erenumab and galcanezumab have the
most studies in this dataset.}
\end{figure}

\begin{verbatim}
## Number of studies: k = 11
## Number of pairwise comparisons: m = 13
## Number of treatments: n = 5
## Number of designs: d = 5
## 
## Random effects model
## 
## Treatment estimate (sm = 'MD', comparison: other treatments vs 'Placebo'):
##                   MD             95%-CI     z  p-value
## Botox A      -3.0000 [-5.6506; -0.3494] -2.22   0.0265
## Eptinezumab  -4.5503 [-6.4759; -2.6248] -4.63 < 0.0001
## Erenumab     -4.2010 [-5.3863; -3.0157] -6.95 < 0.0001
## Galcanezumab -2.0263 [-3.3823; -0.6703] -2.93   0.0034
## Placebo            .                  .     .        .
## 
## Quantifying heterogeneity / inconsistency:
## tau^2 = 1.7773; tau = 1.3331; I^2 = 95.8% [93.8%; 97.2%]
## 
## Tests of heterogeneity (within designs) and inconsistency (between designs):
##                      Q d.f.  p-value
## Total           190.97    8 < 0.0001
## Within designs  184.49    6 < 0.0001
## Between designs   6.47    2   0.0393
\end{verbatim}

The four treatments (Botox A, Eptinezumab, Erenumab, and Galcanezumab
reveal significance in reducing the monthly days of a migraine days
(alpha = 0.05), with Eptinezumab and Erenumab having the largest effects
(p \textless{} 0.001). Additionally, heterogeneity was detected (p
\textless{} 0.0001), suggesting there is variability in treatment
effects across studies.

\begin{figure}
\centering
\includegraphics{final-assessment-mt_files/figure-latex/table-2-1.pdf}
\caption{There are 121,577 observations in the original dataset along
with summary statistics (minimum, maximum, median, mean, and quantiles)
for our variables of interest. Our predictor variables are race
(categorical), deyo (median of 1 and mean of 1.023, indicating more
patients with mild severity), and our rescaled variable age\_cent has a
mean of 0. Length of stay (LOS\_binary) has a mean of 0.022.}
\end{figure}

\begin{verbatim}
## Rankogram (based on 1000 simulations)
## 
## Random effects model: 
## 
##                   1      2      3      4      5
## Botox A      0.1050 0.1620 0.4860 0.2390 0.0080
## Eptinezumab  0.5630 0.3180 0.1100 0.0090 0.0000
## Erenumab     0.3310 0.5070 0.1570 0.0050 0.0000
## Galcanezumab 0.0010 0.0130 0.2470 0.7380 0.0010
## Placebo      0.0000 0.0000 0.0000 0.0090 0.9910
\end{verbatim}

\begin{figure}
\centering
\includegraphics{final-assessment-mt_files/figure-latex/table-3-1.pdf}
\caption{There are 121,577 observations in the original dataset along
with summary statistics (minimum, maximum, median, mean, and quantiles)
for our variables of interest. Our predictor variables are race
(categorical), deyo (median of 1 and mean of 1.023, indicating more
patients with mild severity), and our rescaled variable age\_cent has a
mean of 0. Length of stay (LOS\_binary) has a mean of 0.022.}
\end{figure}

\begin{verbatim}
##               SUCRA
## Eptinezumab  0.8562
## Erenumab     0.7888
## Botox A      0.5317
## Galcanezumab 0.3198
## Placebo      0.0035
## 
## - based on 1000 simulations
\end{verbatim}

\section{Concerns with regard to the
dataset.}\label{concerns-with-regard-to-the-dataset.}

\section{Interpretation of any treatment ranking
statistics}\label{interpretation-of-any-treatment-ranking-statistics}

\section{Appendix}\label{appendix}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(tidyverse)}
\FunctionTok{library}\NormalTok{(readxl)}
\FunctionTok{library}\NormalTok{(netmeta)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{chronic\_migraine\_dataset }\OtherTok{\textless{}{-}} \FunctionTok{read\_excel}\NormalTok{(}\StringTok{"Chronic\_Migraine\_Dataset.xlsx"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# transform dataset to separate treatment type and placebo}
\NormalTok{transformed\_migraine\_dataset }\OtherTok{\textless{}{-}}\NormalTok{ chronic\_migraine\_dataset }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{group\_by}\NormalTok{(study, year) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{trt1name =} \FunctionTok{ifelse}\NormalTok{(trt }\SpecialCharTok{!=} \StringTok{"Placebo"}\NormalTok{, trt, }\ConstantTok{NA}\NormalTok{),}
         \AttributeTok{trt2name =} \FunctionTok{ifelse}\NormalTok{(trt }\SpecialCharTok{==} \StringTok{"Placebo"}\NormalTok{, }\StringTok{"Placebo"}\NormalTok{, }\ConstantTok{NA}\NormalTok{)) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{summarise\_all}\NormalTok{(}\FunctionTok{list}\NormalTok{(}\SpecialCharTok{\textasciitilde{}} \FunctionTok{first}\NormalTok{(}\FunctionTok{na.omit}\NormalTok{(.))))}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{transformed\_migraine\_dataset}\SpecialCharTok{$}\NormalTok{y }\OtherTok{\textless{}{-}} \FunctionTok{as.numeric}\NormalTok{(transformed\_migraine\_dataset}\SpecialCharTok{$}\NormalTok{y)}
\NormalTok{transformed\_migraine\_dataset}\SpecialCharTok{$}\NormalTok{se }\OtherTok{\textless{}{-}} \FunctionTok{as.numeric}\NormalTok{(transformed\_migraine\_dataset}\SpecialCharTok{$}\NormalTok{se)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: NAs introduced by coercion
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# remove TEs or seTEs that are NA}
\NormalTok{transformed\_migraine\_dataset }\OtherTok{\textless{}{-}}\NormalTok{ transformed\_migraine\_dataset }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{drop\_na}\NormalTok{(se) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{select}\NormalTok{(}\SpecialCharTok{{-}}\NormalTok{trt)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{crisp\_arm\_g }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(}\AttributeTok{study =} \StringTok{"Crisp"}\NormalTok{, }\AttributeTok{year =} \StringTok{"2012"}\NormalTok{, }\AttributeTok{y =} \FloatTok{0.70}\NormalTok{, }\AttributeTok{se =} \FloatTok{0.7401}\NormalTok{, }\AttributeTok{na =} \DecValTok{3}\NormalTok{, }\AttributeTok{trt1name =} \StringTok{"Galcanezumab"}\NormalTok{, }\AttributeTok{trt2name =} \StringTok{"Eptinezumab"}\NormalTok{)}

\NormalTok{crisp\_arm\_e }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(}\AttributeTok{study =} \StringTok{"Crisp"}\NormalTok{, }\AttributeTok{year =} \StringTok{"2012"}\NormalTok{, }\AttributeTok{y =} \SpecialCharTok{{-}}\FloatTok{4.90}\NormalTok{, }\AttributeTok{se =} \FloatTok{0.5669}\NormalTok{, }\AttributeTok{na =} \DecValTok{3}\NormalTok{, }\AttributeTok{trt1name =} \StringTok{"Eptinezumab"}\NormalTok{, }\AttributeTok{trt2name =} \StringTok{"Placebo"}\NormalTok{)}

\NormalTok{transformed\_migraine\_dataset }\OtherTok{\textless{}{-}}\NormalTok{ transformed\_migraine\_dataset }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{bind\_rows}\NormalTok{(crisp\_arm\_g, crisp\_arm\_e) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{arrange}\NormalTok{(year)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# create net meta{-}analysis}
\NormalTok{nma }\OtherTok{\textless{}{-}} \FunctionTok{netmeta}\NormalTok{(}\AttributeTok{TE =}\NormalTok{ y, }\AttributeTok{seTE =}\NormalTok{ se, }\AttributeTok{treat1 =}\NormalTok{ trt1name, }\AttributeTok{treat2 =}\NormalTok{ trt2name, }\AttributeTok{studlab =}\NormalTok{ study, }\AttributeTok{data =}\NormalTok{ transformed\_migraine\_dataset, }\AttributeTok{sm =} \StringTok{"MD"}\NormalTok{, }\AttributeTok{ref =} \StringTok{"Placebo"}\NormalTok{, }\AttributeTok{common =} \ConstantTok{FALSE}\NormalTok{, }\AttributeTok{small.values =} \StringTok{"desirable"}\NormalTok{)}
\FunctionTok{print}\NormalTok{(nma)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Number of studies: k = 11
## Number of pairwise comparisons: m = 13
## Number of treatments: n = 5
## Number of designs: d = 5
## 
## Random effects model
## 
## Treatment estimate (sm = 'MD', comparison: other treatments vs 'Placebo'):
##                   MD             95%-CI     z  p-value
## Botox A      -3.0000 [-5.6506; -0.3494] -2.22   0.0265
## Eptinezumab  -4.5503 [-6.4759; -2.6248] -4.63 < 0.0001
## Erenumab     -4.2010 [-5.3863; -3.0157] -6.95 < 0.0001
## Galcanezumab -2.0263 [-3.3823; -0.6703] -2.93   0.0034
## Placebo            .                  .     .        .
## 
## Quantifying heterogeneity / inconsistency:
## tau^2 = 1.7773; tau = 1.3331; I^2 = 95.8% [93.8%; 97.2%]
## 
## Tests of heterogeneity (within designs) and inconsistency (between designs):
##                      Q d.f.  p-value
## Total           190.97    8 < 0.0001
## Within designs  184.49    6 < 0.0001
## Between designs   6.47    2   0.0393
\end{verbatim}

The treatments reduce the monthly days of a migraine days. All
treatments are significant, with Eptinezumab and Erenumab having the
largest effects (p \textless{} 0.001).

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{netgraph}\NormalTok{(nma, }\AttributeTok{plastic =} \ConstantTok{FALSE}\NormalTok{, }\AttributeTok{points =} \ConstantTok{TRUE}\NormalTok{, }\AttributeTok{col =} \StringTok{\textquotesingle{}darkblue\textquotesingle{}}\NormalTok{, }\AttributeTok{thickness =} \StringTok{"number.of.studies"}\NormalTok{, }\AttributeTok{lwd =} \FloatTok{2.7}\NormalTok{, }\AttributeTok{cex.points =} \DecValTok{4}\NormalTok{, }\AttributeTok{offset =} \FloatTok{0.05}\NormalTok{, }\AttributeTok{scale =} \FloatTok{1.1}\NormalTok{, }\AttributeTok{col.points =} \StringTok{\textquotesingle{}red\textquotesingle{}}\NormalTok{, }\AttributeTok{seq =} \DecValTok{1}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{final-assessment-mt_files/figure-latex/unnamed-chunk-14-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Basic network effects forest plot}
\FunctionTok{forest}\NormalTok{(nma)}
\end{Highlighting}
\end{Shaded}

\includegraphics{final-assessment-mt_files/figure-latex/unnamed-chunk-15-1.pdf}

Standardized mean differences Larger confidence intervals, less
precision

All of the studies do not cross the line of no effect, revealing
significance

Represents the effect size, such as mean difference (MD), odds ratio
(OR), risk ratio (RR), etc. Usually includes a line at 0 (for MD) or 1
(for OR/RR) indicating no effect or no difference between treatments. A
vertical line at 0 (for MD) or 1 (for OR/RR) represents the line of no
effect. Each horizontal line represents the confidence interval (CI) of
the effect size for a particular comparison. The square or diamond at
the center of each line represents the point estimate of the effect
size. For MD, a point estimate to the left of 0 indicates that the
treatment is better than the comparator (e.g., less pain), Narrow
intervals indicate more precise estimates, while wider intervals
indicate less precision.

Eptinezumab shows the most precision shows a significant reduction in
migraines, with a narrower CI indicating more precise estimates.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{76}\NormalTok{)}
\FunctionTok{rankogram}\NormalTok{(nma) }\CommentTok{\# probabilities that any of our 5 treatments are the best treatment }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Rankogram (based on 1000 simulations)
## 
## Random effects model: 
## 
##                   1      2      3      4      5
## Botox A      0.1050 0.1620 0.4860 0.2390 0.0080
## Eptinezumab  0.5630 0.3180 0.1100 0.0090 0.0000
## Erenumab     0.3310 0.5070 0.1570 0.0050 0.0000
## Galcanezumab 0.0010 0.0130 0.2470 0.7380 0.0010
## Placebo      0.0000 0.0000 0.0000 0.0090 0.9910
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{pg }\OtherTok{\textless{}{-}} \FunctionTok{rankogram}\NormalTok{(nma, }\AttributeTok{cumulative =} \ConstantTok{TRUE}\NormalTok{)}

\FunctionTok{plot}\NormalTok{(pg)}
\end{Highlighting}
\end{Shaded}

\includegraphics{final-assessment-mt_files/figure-latex/unnamed-chunk-16-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{netrank}\NormalTok{(pg) }\CommentTok{\# average proportion that any of our treatments is better than other interventions}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##               SUCRA
## Eptinezumab  0.8562
## Erenumab     0.7888
## Botox A      0.5317
## Galcanezumab 0.3198
## Placebo      0.0035
## 
## - based on 1000 simulations
\end{verbatim}

It displays the probabilities (based on simulations) of each treatment
being ranked from 1 to 5. The output you've provided shows the
probabilities for each treatment (Botox A, Eptinezumab, Erenumab,
Galcanezumab, Placebo) being ranked from 1st to 5th based on 1000
simulations.

For Botox A, in 10.5\% of simulations, it was ranked 1st, in 16.2\% it
was ranked 2nd, and so on. For Placebo, in 99.1\% of simulations, it was
ranked 5th.

The rankogram is based on results from a random effects model
assumption. This model allows for variability in treatment effects
across studies, which is reflected in the distribution of ranks seen in
the rankogram.

When heterogeneity is minimal, a fixed effects model might be
appropriate. When heterogeneity is minimal, the assumption that all
studies are estimating the same underlying effect size is more likely to
hold true. This simplifies the model as less variation needs to be
accounted for, making the frequentist approach both efficient and
effective. If there is some minor heterogeneity, a random effects model
can still be used to account for this small degree of variability.

Eptinezumab and Erenumab are likely to be the most effective treatments,
followed by Botox A and Galcanezumab.

\section{References}\label{references}

\end{document}
